### PR TITLE
feat: new style for activity creation

### LINKED ISSUE #896: Improve the UX for step title in activity creation form
Currently, only users with staff privileges can see the activity creation form. So, I am sharing screenshots below. **Note:** Please don't request staff access; it is currently not possible.

In the "Step" section in the activity creation form, it is not clear that "Step 1: Enter title here" is clickable and accepts text input. This design needs improvement. Perhaps, we can add a new input field similar to the step description for the title.

### PR DESCRIPTION
**Pull request by yokwejuste**
## Summary

Description of PR here...
Closes #896 

## Changes

- Activoty creation form

## Screenshot
**Before**
image

**Progress:**
image
image

**The End**
image
image

### CODE REVIEW

**Comment by brrkrmn** [comment]
Hey @yokwejuste, I assume you added a gap above the second label, would you mind adding the final screenshots of the view?

**Comment by yokwejuste** [comment]
> Hey @yokwejuste, I assume you added a gap above the second label, would you mind adding the final screenshots of the view?

sure,

@brrkrmn 
image
image

**Review by tuxology — APPROVED** [review]
LGTM for now. We will have to improve all these components properly eventually.

**Comment by yokwejuste** [comment]
> LGTM for now. We will have to improve all these components properly eventually. 

Definitely,

Also improving on components reusability

**Pull request merged**
