### PR TITLE
Fix labels for publish type corrected

### LINKED ISSUE #581: Draft projects should not show up in the search bar for user who created it
## The Bug
Projects created in draft mode by a user show up in search results for them on the landing page through the search bar

## To Reproduce

- Visit https://zubhub.unstructured.studio/
- Login
- Create a project in draft mode
- Go back to the home screen
- Search for the project you created
- It shows up in the results

## Expected behavior
Draft projects should not show up in the search results

### PR DESCRIPTION
**Pull request by darechan**
## Summary

The label for publish type was named incorrectly so as per the discussion in this [thread](https://github.com/unstructuredstudio/zubhub/issues/556#issuecomment-1453884839) the labeling was corrected 

Closes #581

## Screenshots

1. When the project is set to `only me` it moves to draft
image
image

2. When the project is set to `All registered zubhub users`
image
image

3. When the project is set to `Only a few zubhub users`
image

### CODE REVIEW

**Comment by iamhks** [comment]
Isn't this PR a duplicate of @cherish2003's https://github.com/unstructuredstudio/zubhub/pull/678/files?

**Comment by darechan** [comment]
> Isn't this PR a duplicate of @cherish2003's https://github.com/unstructuredstudio/zubhub/pull/678/files?

This is for #581

**Comment by iamhks** [comment]
> > Isn't this PR a duplicate of @cherish2003's https://github.com/unstructuredstudio/zubhub/pull/678/files?
> 
> This is for #581

That means the issue itself is a combined duplicate of #592 and #593

**Comment by tuxology** [comment]
@iamhks you are correct. The real improvement I was expecting from #581 was improving and building upon #556 which would require more deeper work and UX. For now, we will go with merging wither this PR or #678 just to keep the quick fix going. @darechan We will close this PR and #581 once we merge either of these small fixes.

**Comment by tuxology** [comment]
@darechan I am closing this as we just went ahead with the simple fix by @cherish2003 in #699 Thanks for reporting. I think lets keep #581 alive until we find a roper UX for resolving the issue properly

**Pull request closed without merging**
