### PR TITLE
Password reset not checking if user already has an account before validating the request

### LINKED ISSUE #654: Password reset not checking if user already has an account before validating the request.
**Describe the bug**
When we access the password [reset page ](https://zubhub.unstructured.studio/password-reset), and we add an email address that isn't tied to an existing user in the system, we get a success message from the API saying `Password reset e-mail has been sent`
This should not be the case as password reset emails should only be sent to those that had previously created an account on zubhub.

**To Reproduce**

1. Go to https://zubhub.unstructured.studio/password-reset
2. Enter a creative email that you think doesn't exist on the app 
3. Submit the form
4. See error or check the network tab to see the response of the API

**Expected behavior**
When an email doesn't exist on the platform, the API should indicate it and we can let the user know that the email they used doesn't exist on the platform. This will also help us not to send unnecessary emails to people that don't have accounts.

### PR DESCRIPTION
**Pull request by yaya-mamoudou**
## Summary
When a user tries to reset their password, we check if the provided email is linked to an existing account before sending a success request. Otherwise, an appropriate response is sent to inform the user that an account with the email they provided was not found and they should verify their email and try again

Closes #654 

## Changes

- Created a Custom password reset class that extends the PASSWORD_RESET_SERIALIZER  provided by Django rest framework and added another layer of verification to check if email exists in the DB or else return an error.
-  Cleared the form error when submitting In case there was an error displayed from the previous submission.

## Screenshots
https://www.loom.com/share/4835dd48ada641daab233d093bd60e94

### CODE REVIEW

**Review by tuxology — COMMENTED** [review]
Thanks, I've reviewed this 🎉 No real changes needed, but we would have to wait a bit here since I want to test this on staging first @yaya-mamoudou

**Comment by yaya-mamoudou** [comment]
> Thanks, I've reviewed this 🎉 No real changes needed, but we would have to wait a bit here since I want to test this on staging first @yaya-mamoudou

Alright, @tuxology. Thanks🥳

**Review by tuxology — APPROVED** [review]
So I did one test on this, and it seems to work on staging. I will merge this a bit later after all other fixes are done. Thanks 🙏

**Comment by yaya-mamoudou** [comment]
> So I did one test on this, and it seems to work on staging. I will merge this a bit later after all other fixes are done. Thanks 🙏

Thanks, @tuxology. I am so happy this got approved. First time writing python code. This issue forced me to learn the basics of python and Django in 3 days. 🎉🎊

**Pull request merged**
