### PR TITLE
Fix using svg for Play icon instead of png

### LINKED ISSUE #620: Use of SVG instead of PNG in play icon
## The bug
The png for play icon gets blurred out based on screen resolution so replacing the png to an svg for the same would be a great quick fix

## Screenshots
image

### PR DESCRIPTION
**Pull request by darechan**
## Summary

Initially the `Play Icon` for projects had a low resolution png which was replaced by a svg for the same.
Closes #620 

## Changes

- Play-icon png was replaced by play-icon svg
- All the path referencing the png were altered
- The SVG was styled to fit the project card

## Screenshots

image

### CODE REVIEW

**Comment by tuxology** [comment]
@darechan Nice 🎉 Can we add a small shadow to it just to keep it consistent with other shadowy elements like card etc? And also the request about color change when hovering? Just slight hue/shade change can be ok. No need to completely make it red/yellow on hover.

**Comment by darechan** [comment]
@tuxology for sure- that would add in a bit more detail

**Comment by darechan** [comment]
@tuxology 
image

shall I add more blur?

**Comment by tuxology** [comment]
Yes, please see that it is close to the blur/direction as in card

**Comment by darechan** [comment]
> Yes, please see that it is close to the blur/direction as in card

image

Updated please check!

**Review by tuxology — APPROVED** [review]

**Pull request merged**
