### PR TITLE
Add search autocomplete

### PR DESCRIPTION
**Pull request by AndrewLester**
## Summary

Adds tag-based autocomplete to search.
Waiting on #385 

## Changes

- Uses trigram similarity matching for tag search to reflect search query principles.
- Uses material ui autocomplete wrapped textfields for autocomplete

## Screenshots
image

image

image

image

## Requests / Responses

image

## Outstanding issues
- [x] Image sizing

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for adapting to the changes and getting this done quickly! Albert and I talked a little bit more about the result formatting for the projects filter and we felt that the author should be vertically centered in relation to the search result bold text if possible. Also, we didn't anticipate that the project thumbnails could end up being different sizes so we're thinking of maybe including part of the description of the project in grey text like linkedIn does instead of the project thumbnails so that alignment isn't an issue. We can discuss this more during dev night though.

**Comment by NdibeRaymond** [comment]
@AndrewLester you can merge this when everyone else thinks it's fine. I've pulled the change into my local machine and done basic manual testing, but It will take hours to properly review the code involved due to the number of files changed, most of which are not related to the actual change but are more like changes from the auto formatter in your local machine. Next time if you can, avoid making heavy formatting changes like this along side feature change, because that makes it difficult to differentiate between relevant changes to review and formatting changes.

**Comment by tuxology** [comment]
@NdibeRaymond This actually reminds us that once things are a bit stable, we should pause all merges, lint and auto-format all code and do a big PR (which we know won't break anything since its just formatting). Post that, we will either include some Github bots that call out linting and also suggest formatting guidelines here. I'll create an issue for this so we remember it.

**Comment by tuxology** [comment]
@AndrewLester and @ajain1921 Lets merge this, this is an awesome feature!!

**Comment by tuxology** [comment]
@ajain1921 Can you review, test and merge this? @AndrewLester also resolve conflicts where present - this is getting too big and the incoming PRs will face issues in resolving conflicts if we delay this

**Review by ghost — APPROVED** [review]
Great work!

**Pull request merged**
