### PR TITLE
Validate and compress uploaded media for project creation

### PR DESCRIPTION
**Pull request by Mutombe**
##Summary
This pull request (PR) addresses the issue #340 by implementing validation and compression for uploaded media.

##Changes
The following changes have been made in this PR:

Compression of Uploaded Images: Previously, when users uploaded images, they were stored in their original sizes, which could result in large file sizes. In this PR, a new feature has been added to compress the uploaded images. By compressing the images, their file sizes are reduced, resulting in optimized storage and improved performance.

##Technical Details
To achieve image compression, the following steps were taken:

1. Compression Settings: The compression settings, such as the desired image quality and maximum file size, were configured based on project specifications. These settings can be adjusted as needed to achieve the desired balance between image size reduction and image quality preservation.

### CODE REVIEW

**Comment by NdibeRaymond** [comment]
@tuxology is anyone allowed to work on any task even when another person indicated interest first?

**Comment by NdibeRaymond** [comment]
I also think we should go back and discuss more about this task before proceeding to work on it. I'm dropping a few comments to get the conversation started

**Comment by Mutombe** [comment]
> I also think we should go back and discuss more about this task before proceeding to work on it. I'm dropping a few comments to get the conversation started

Ok. Thank you.

**Comment by Mutombe** [comment]
> I also think we should go back and discuss more about this task before proceeding to work on it. I'm dropping a few comments to get the conversation started

Ok. Thank you.

**Pull request closed without merging**
