### PR TITLE
(fix): Creator profile gets margin

### LINKED ISSUE #1005: Creator profile is stretched for non-logged-in users
In non-logged-in states, the creator profile appears stretched with no margins on the left and right.

Image

### To Reproduce:
- Visit https://zubhub.unstructured.studio/
- Make sure you're signed out
- Click on the creator of any project under 'featured projects'

### PR DESCRIPTION
**Pull request by brrkrmn**
## Summary

Creator profile content lacked margin in the following instances:
1. for non-logged-in users
3. for logged-in users between 740-960px of screen width

Closes #1005 

## Changes

- For logged-in users, the profile content is rendered within a grid inside `DashboardLayout`, whose styles determine the margins around this content. But in the non-logged-in state, the profile content is rendered on its own. That is why non-logged-in users do not see those margins. However, applying the necessary margins to the content itself results in too much margin for the logged-in state (content's margin + dashboardLayout's margin). That's why I created a new `nonLoggedInRoot` class or the content to only apply margin for non-logged-in state.
- Removed margins of separate sections and applied margin to the content's root instead. 

### Before
image

### After
image

### CODE REVIEW

**Comment by NdibeRaymond** [comment]
code looks good. I haven't tested it manually yet

**Comment by NdibeRaymond** [comment]
@brrkrmn I already rebased this on top of master and got pre-commit passing.
the steps are:
* rebase this branch on top of master.
* squash the commits in this PR from 2 commits to 1.
* undid the commit in a way that the changes weren't discarded (git reset --soft HEAD~1)
* followed the instruction in the readme to set up pre-commit
* run `pre-commit` to see what the errors were
* fix the errors, commit and force push

**Comment by NdibeRaymond** [comment]
had to rework this PR a bit. I think it's ok now. merging after pre-commit has completed successfully

**Comment by yokwejuste** [comment]
> had to rework this PR a bit. I think it's ok now. merging after pre-commit has completed successfully

okay...

**Comment by NdibeRaymond** [comment]
more css and eslint fixes

**Pull request merged**
