### PR TITLE
UX enhancements to "publish option" in "create" form

### LINKED ISSUE #441: UX enhancements to "publish option" in "create" form
First, some text changes are needed in the "publish option" field, issue is filed here: https://github.com/unstructuredstudio/zubhub/issues/440. 

Second comes UX improvements, which have primarily to do with options in the dropdown. I think the four options are confusing and not entirely related to publishing. 

I think the dropdown should only have two options, "Public" and "ZubHub Users". "Draft" can be moved out of this dropdown, as saving the project in draft mode means the changes are still in progress and not published. So either "Draft" should be named "Private" or appear next to the "Create Project" button as "Save as draft" and "Create Project" can be changed to "Publish Project" or "Publish Changes".

Then, the "Preview" option in its current shape and form is very confusing. It doesn't convey its intended purpose, which is that it allows anyone to share their project with other users for preview. One idea - this option can be offered as soon as the project is saved below the create form itself, just like how blogging platforms like Ghost allow.

Screen Shot 2022-04-21 at 5 44 54 PM

### PR DESCRIPTION
**Pull request by godsakani**
Closes #441, 
## Changes

- Change text options in the "public option"  in the "create"  form.

## Screenshots
chan

### CODE REVIEW

**Review by srish — APPROVED** [review]
@godsakani Could you remove the line you added in `projectDetailsStyles.js`? Other than that these changes look good to me. 

@tuxology Please help merge.

**Comment by godsakani** [comment]
> @godsakani Could you remove the line you added in `projectDetailsStyles.js`? Other than that these changes look good to me.
> 
> @tuxology Please help merge.

Ok @srish  i will do just that

**Comment by godsakani** [comment]
> @godsakani Could you remove the line you added in `projectDetailsStyles.js`? Other than that these changes look good to me.
> 
> @tuxology Please help merge.

@srish everything good now just removed it

**Comment by tuxology** [comment]
@godsakani Can you confirm that the order of the dropdown is same as the order we discussed here: https://github.com/unstructuredstudio/zubhub/issues/441#issuecomment-1128755904

The screenshot you shared shows otherwise

**Comment by godsakani** [comment]
@tuxology is same

**Review by tuxology — APPROVED** [review]

**Pull request merged**
