### PR TITLE
Show error messages in Login and EditProfile forms for required fields

### LINKED ISSUE #838: Login and EditProfile forms not showing error messages when required fields left empty
**The Problem**
Log in and Edit Profile forms do not show error messages when required. In Edit Profile form, the user does not get any feedback on why the form is not submitted.

**To Reproduce**

Login ->
1. Go to https://zubhub.unstructured.studio/login
2. Click on login without typing in the fields
3. See the error message for password input but not for username

Edit Profile ->
1. Go to https://zubhub.unstructured.studio/edit-profile
2. Remove all fields' text
3. Click Edit Profile
4. See the error message for username and location, but not for other required fields

**Expected behavior**
It is expected to inform the user about why the form is not submitting when the required fields left empty.

**Videos**
See that the user does not receive any error when trying to submit the form with empty fields:

https://github.com/unstructuredstudio/zubhub/assets/92817363/d9e97f0f-41bd-429b-ab52-475b982c5e03

https://github.com/unstructuredstudio/zubhub/assets/92817363/45e00101-254d-4509-bae1-c372076641fa

### PR DESCRIPTION
**Pull request by brrkrmn**
## Summary

When trying to submit the login and editProfile forms without filling the required fields, no error message or feedback is given to the user. 
If the user focuses on an input and then leaves it empty, the error message is seen, however, if the input is blank and not touched by the user until the submission, no message is shown. 

Closes #838

## Changes

- The inputs that should show error messages are triggered by `setFieldTouched` in their submit functions. I chose this approach for consistency because the signup form uses it for all its inputs.
- Through Yup validation, phone and email fields in the edit profile form now show an error message if both are empty.

## Final Results:

https://github.com/unstructuredstudio/zubhub/assets/92817363/46aa782b-c00f-4da4-805b-f5a4fbdf8aeb

ts/92817363/070d39bb-3cc7-4f56-8c10-342d792138b1

https://github.com/unstructuredstudio/zubhub/assets/92817363/63d646cc-f6a7-4717-98aa-6dc2c178aa0e

### CODE REVIEW

**Review by NdibeRaymond — APPROVED** [review]
I tested this patch @tuxology and it works as described, but I've been away from the project for some time now so you should probably take a look too especially when it comes to commit practices

**Comment by NdibeRaymond** [comment]
@brrkrmn it seems like the following files `EditTeam.jsx, editTeamScripts.js` is similar to what we  have for `EditProfile`. Maybe you can investigate and see if that be fixed too?

**Comment by brrkrmn** [comment]
> @brrkrmn it seems like the following files `EditTeam.jsx, editTeamScripts.js` is similar to what we have for `EditProfile`. Maybe you can investigate and see if that be fixed too?

Sure, on it ☺️

**Comment by brrkrmn** [comment]
@NdibeRaymond Hey, my code is up to date, but I cannot see anything related to teams. How can I test the EditTeam view?

**Comment by brrkrmn** [comment]
> @brrkrmn it seems like the following files `EditTeam.jsx, editTeamScripts.js` is similar to what we have for `EditProfile`. Maybe you can investigate and see if that be fixed too?

I implemented the same solution for these files in #857, waiting for reviews 🙂

**Pull request merged**
