### PR TITLE
Fixed issue 211

### PR DESCRIPTION
**Pull request by alicendeh**
## Summary
Realigned buttons in project page and reduced vertical spacing between clab,bookmark,view button row and photos div

## Changes

- Realigned buttons in Project Page
-  Reduced vertical spacing between clab,bookmark,view button row and photos div

## Screenshots

Screenshot from 2022-04-08 05-28-29

### CODE REVIEW

**Comment by alicendeh** [comment]
Here @NdibeRaymond. I closed the other PR and opened this one. Please have a look

**Comment by tuxology** [comment]
Thanks @alicendeh . The Clap-bookmark-views "button" does not look ok still since its all squashed together on the left while there is empty space on right. I have some ideas to really make this way better. It would go a bit out of scope of #211 's requirements. 

So for now, essentially we could just right align the complete button (containing all 3 elements) and reduce width so that it looks more balanced. Also introduce a bit of padding between text and the icon as well. This will do for now and we can improve this in another iteration.

**Comment by NdibeRaymond** [comment]
@alicendeh when you upload the patch for @tuxology 's review we will merge this.

**Comment by alicendeh** [comment]
> Thanks @alicendeh . The Clap-bookmark-views "button" does not look ok still since its all squashed together on the left while there is empty space on right. I have some ideas to really make this way better. It would go a bit out of scope of #211 's requirements.
> 
> So for now, essentially we could just right align the complete button (containing all 3 elements) and reduce width so that it looks more balanced. Also introduce a bit of padding between text and the icon as well. This will do for now and we can improve this in another iteration.

Got it. Working on that.

**Comment by alicendeh** [comment]
> @alicendeh when you upload the patch for @tuxology 's review we will merge this.

okay, @NdibeRaymond. I was working on the mobile section so I couldn't modify this the other day. But am on it now.

**Comment by alicendeh** [comment]
Hello @tuxology and @NdibeRaymond. I did the necessary corrections requested.
1. Gave the same  padding between the clap-bookmark and view icon
2. Added spacing between the text and the icon
3. Aligned the items to the right

**OUTPUT**

Screenshot from 2022-04-11 08-25-36

**Comment by tuxology** [comment]
This looks better. We are almost there! Can we remove full width of the "clap-bookmark-views" element and just have it enough to cover the 3 "buttons" (and the whole button remains aligned right as well)?

**Comment by alicendeh** [comment]
> This looks better. We are almost there! Can we remove full width of the "clap-bookmark-views" element and just have it enough to cover the 3 "buttons" (and the whole button remains aligned right as well)?

Please @tuxology am a little lostZ 
What do you mean by full width please?

**Comment by tuxology** [comment]
@alicendeh We do something like this for now

image

This design will eventually change in a few months as we optimize the position of these elements, but for now, this will help!

**Comment by alicendeh** [comment]
Alright, I see now, Thanks.
I will provide these change in a while

**Comment by alicendeh** [comment]
Hello @tuxology I have  done the change you requested

**OUTPUT**
Screenshot from 2022-04-13 07-23-20

**Comment by alicendeh** [comment]
Hello @tuxology please you havent responded to this yet

**Review by tuxology — APPROVED** [review]
LGTM :rainbow_flag: Lets checkout package-lock.json from `master` branch and then merge it

**Comment by alicendeh** [comment]
Hello @tuxology  the content of the package-lock.json is same as whats currently on the repo

**Comment by tuxology** [comment]
@alicendeh Looks like there is a difference (https://github.com/unstructuredstudio/zubhub/pull/390/files#diff-1e460fd2de8f7f6c83ff9c821068937ff5f1be7769d2ec1679a1280f19d8263a). Did you update your `master` branch locally before diffing? The `caniuse-lite` package seems to have been updated

**Comment by alicendeh** [comment]
@tuxology  please have a look now

**Review by tuxology — APPROVED** [review]
LGTM :rainbow_flag:

**Comment by ghost** [comment]
@alicendeh @tuxology It seems like this PR adds the ability to select multiple categories on the Create Project Form. I believe it's leading to Issue #424. Is this a feature we want? For now, I'm going to remove the multiple category addition to fix the issue and maybe discuss if this is something we want in the future.

**Comment by tuxology** [comment]
@ajain1921 I think yes, you are right. I merged too soon. This has some stale code from the other category issue (possibly should have been included in #395) that we decided not to merge. Thanks for removing he multiple category code that got included in this PR.

@alicendeh Please take a note for next PRs that they should not have stale code from other issues. A general approach is to always create separate feature branched from the main `master` branch and keep your feature branch up to date. Unless the features are interlinked (which is not the case here) never branch from your own active feature branch. This can cause issues like the one we see here

**Comment by alicendeh** [comment]
Noted @tuxology thqnks. This won't happen again

**Pull request merged**
