### PR TITLE
improveSearchBar: centralized the search bar and used the dark theme

### LINKED ISSUE #177: Improvements to search bar
- [ ] Use darker colored search bar

Screen Shot 2021-05-25 at 8 58 55 PM

- [ ] Center the searchbar on large screens. 
Screen Shot 2021-05-25 at 8 59 02 PM

- [ ] Search bar appears funny in mobile view
Screen Shot 2021-05-25 at 8 59 02 PM

### PR DESCRIPTION
**Pull request by Jumeb**
Improvements to search bar.
- Centralized the search bar.
- Change the search bar to a dark theme.

Centralized for larger devices
image

dark theme for all devices
image

Centralized for smaller devices like tables
image

fixes #177

### CODE REVIEW

**Review by tuxology — APPROVED** [review]
Generally, LGTM :rainbow_flag: I'll let @NdibeRaymond merge this. Can you also add a screenshot in the description to show how it looks?

**Comment by NdibeRaymond** [comment]
Thanks for making this PR @Jumeb! 
I noticed are lots of dirty diffs in your PR, particularly in the package-lock.json file. I understand that it's probably your local development environment that is adding these diffs and it's not your fault. Perhaps you can clean it up a bit?
If you can't avoid dirty diffs in the package-lock.json file, a quick way to fix it before committing is to run `git checkout package-lock.json` in the folder containing the package-lock.json file, then git add . and git commit.

**Review by NdibeRaymond — CHANGES_REQUESTED** [review]
See previous comment about dirty diffs.

**Comment by NdibeRaymond** [comment]
Hello @Jumeb , I noticed you deleted the package-lock.json file. My review about cleaning up dirty diffs wasn't about deleting the package-lock.json file, rather I was talking about returning the package-lock.json to it's initial state before your local dev environment made changes to it. Right now you should just copy the package-lock.json from master branch to your branch and that'd solve the issue. Do this, then let's merge your PR

**Comment by NdibeRaymond** [comment]
Also resolve the conflict in pageWrapperStyles.js and squash your commits into one (this can be done using git rebase then force push. You can read it up)

**Comment by Jumeb** [comment]
@NdibeRaymond thanks for the tips, everyday is an opportunity to learn. I just made the changes and changed the **package-lock.json** file to its original state. Always had problems with _git rebase_ hope I did it right this time.

**Comment by tuxology** [comment]
@Jumeb Take a look at latest changes we've merged on http://zubhub.unstructured.studio. The search bar's behavior and UX has changed a bit. Can you adapt to that and rebase in addition to changes @NdibeRaymond requested? Then we can merge this one :+1:

**Comment by AndrewLester** [comment]
@Jumeb Also, feel free to fix this current issue with the search category selector in the UI. Should just need to override the `min-width: 0` (and set it to `unset`) on the FormControl element which wraps the category selector, then give the outlined input's form control a `flex-shrink: 1`.
image

**Comment by Jumeb** [comment]
I’m on it @tuxology and @AndrewLester

**Comment by Jumeb** [comment]
> @Jumeb Also, feel free to fix this current issue with the search category selector in the UI. Should just need to override the `min-width: 0` (and set it to `unset`) on the FormControl element which wraps the category selector, then give the outlined input's form control a `flex-shrink: 1`. image

Thanks for the tip, it worked perfectly. I have solved the issues

**Comment by tuxology** [comment]
@NdibeRaymond Should we merge this one?

**Comment by NdibeRaymond** [comment]
> @NdibeRaymond Should we merge this one?

I'll attempt removing the package-lock.json change

**Comment by NdibeRaymond** [comment]
@Jumeb can you try clicking on "allow edits by maintainers" on this PR? the PR made a large change to the package-lock and should be reverted back before merging.

**Comment by Jumeb** [comment]
> @Jumeb can you try clicking on "allow edits by maintainers" on this PR? the PR made a large change to the package-lock and should be reverted back before merging.

Sorry for the troubles, I just clicked the option to **allow edit by maintainer**

**Pull request merged**
