### PR TITLE
fixed uneven padding / spacing between icons on the video's button bar, more visible when the bar becomes horizontal.

### LINKED ISSUE #173: Uneven padding / spacing between icons on the video's button bar
Uneven padding / spacing between icons on the video's button bar, more visible when the bar becomes horizontal. The horizontal bar is full width which is  not ideal as well. It should be grouped on the right with some indication that they are clickable. Before working on this, it may be important to sketch some ideas and gather feedback

Screen Shot 2021-05-25 at 8 38 19 PM

### PR DESCRIPTION
**Pull request by godsakani**
## Summary
Fix #173 
Closes #173 
I changed the display to inline-flex, I gave a flex direction to column and align the items to left using justify-content which help fix the mobile horizontal view. Also for the desktop view I gave a padding-right and also height to align the contents.

## Changes
- projectDetailsstyle.js

## Screenshots
mob
161259516-f4b17142-9f77-48ab-80ab-d89c5ae5671d
tab

### CODE REVIEW

**Review by tuxology — CHANGES_REQUESTED** [review]
@godsakani Thanks :pray: There are conflicts since some styles have been already updated as part of #390. Make sure you keep the styles of the right alignment of horizontal bar and the spacing between the text and icon. The spacing also is very close to what was fixed in #390 so there are many overlaps in this PR. There could be very few improvements still (the left padding is not same as right padding for example I think). 

In addition, we need to change icon order, but this is a larger UX improvement. I recommend you propose better UX than what is already there. Some ideas are: moving the bookmark as a separate button on far right, changing the background of "views" since it is a non-interactive element and its confusing to group them in same container etc. So all this needs some fresh ideas.

**Comment by godsakani** [comment]
> @godsakani Thanks 🙏 There are conflicts since some styles have been already updated as part of #390. Make sure you keep the styles of the right alignment of horizontal bar and the spacing between the text and icon. The spacing also is very close to what was fixed in #390 so there are many overlaps in this PR. There could be very few improvements still (the left padding is not same as right padding for example I think).
> 
> In addition, we need to change icon order, but this is a larger UX improvement. I recommend you propose better UX than what is already there. Some ideas are: moving the bookmark as a separate button on far right, changing the background of "views" since it is a non-interactive element and its confusing to group them in same container etc. So all this needs some fresh ideas.

Ok @tuxology  thanks for the review and correction.

**Comment by godsakani** [comment]
@tuxology 
Am just from browsing the #390 and is exactly the same thing.
please what should i do?

**Comment by tuxology** [comment]
I suggest we close this PR. If you feel there could be new improvements that can be done to existing UI, we can keep it open. Let me know!

**Comment by godsakani** [comment]
> I suggest we close this PR. If you feel there could be new improvements that can be done to existing UI, we can keep it open. Let me know!

@tuxology  Is ok if we close the PR. Because alicendeh  already did the improvement as you requested.

**Pull request closed without merging**
