### PR TITLE
fix: comment not showing on Featured Projects

### PR DESCRIPTION
**Pull request by aqsaaqeel**
## Summary

The Projects under Featured Projects list are showing comments count now.
Closes #85, Closes #22

## Solution

The response from ```staff-picks``` API did not have a ```comments_count``` field. I have added it under the ```serializers.py / ProjectSerializer```

## Screenshots
Screenshot from 2023-10-04 05-41-07

## Requests / Responses
**Request**

GET `/api/projects/staff-picks/`

**Response**
```
[
    {
        "id": "226bd96d-8f3d-4d85-85df-b07469a4bdc5",
        "title": "Featured Projects",
        "description": "Curated by Unstructured Studio team",
        "projects": {
            "results": [
                {
                    "id": "86a0456d-f86b-4b12-ace8-28d2ed9557fc",
                    "creator": {
                        "id": "b7c4ede2-b2e9-475d-a517-63e3ef407d2f",
                        "username": "aqsacodes",
                        "avatar": "https://robohash.org/aqsacodes",
                        "comments": [
                            {
                                "id": 2,
                                "project": null,
                                "creator": {
                                    "id": "537c5432-daed-412a-8616-b140563ed8a7",
                                    "username": "dummy",
                                    "avatar": "https://robohash.org/dummy"
                                },
                                "text": "hello",
                                "created_on": "2023-10-03T23:31:49.614297Z",
                                "replies": []
                            }
                        ],
                        "bio": "",
                        "followers": [],
                        "following_count": 0,
                        "projects_count": 2,
                        "members_count": null,
                        "tags": [
                            "creator"
                        ],
                        "badges": [
                            "Hatchling"
                        ]
                    },
                    "title": "fvz",
                    "description": "<p>sds</p>",
                    "images": [
                        {
                            "image_url": "http://localhost:8001/project_images/95uDEPJ9_kJP4VJ5m1Tx2",
                            "public_id": "project_images/95uDEPJ9_kJP4VJ5m1Tx2"
                        }
                    ],
                    "video": "",
                    "materials_used": "Paint",
                    "tags": [],
                    "category": [
                        "Toys"
                    ],
                    "likes": [],
                    "saved_by": [],
                    "views_count": 2,
                    "comments": [
                        {
                            "id": 6,
                            "project": "86a0456d-f86b-4b12-ace8-28d2ed9557fc",
                            "creator": {
                                "id": "537c5432-daed-412a-8616-b140563ed8a7",
                                "username": "dummy",
                                "avatar": "https://robohash.org/dummy"
                            },
                            "text": "hello again",
                            "created_on": "2023-10-03T23:36:55.329495Z",
                            "replies": []
                        }
                    ],
                    "created_on": "2023-09-30T16:24:14.918966Z",
                    "publish": {
                        "type": 4,
                        "visible_to": []
                    },
                    "comments_count": 0
                },
                {
                    "id": "9fac8df9-fe5c-46b0-ad50-d077e7f1f388",
                    "creator": {
                        "id": "b7c4ede2-b2e9-475d-a517-63e3ef407d2f",
                        "username": "aqsacodes",
                        "avatar": "https://robohash.org/aqsacodes",
                        "comments": [
                            {
                                "id": 2,
                                "project": null,
                                "creator": {
                                    "id": "537c5432-daed-412a-8616-b140563ed8a7",
                                    "username": "dummy",
                                    "avatar": "https://robohash.org/dummy"
                                },
                                "text": "hello",
                                "created_on": "2023-10-03T23:31:49.614297Z",
                                "replies": []
                            }
                        ],
                        "bio": "",
                        "followers": [],
                        "following_count": 0,
                        "projects_count": 2,
                        "members_count": null,
                        "tags": [
                            "creator"
                        ],
                        "badges": [
                            "Hatchling"
                        ]
                    },
                    "title": "New proj",
                    "description": "<p>jkjbk</p>",
                    "images": [
                        {
                            "image_url": "http://localhost:8001/project_images/dNhIE21WW8XRtnIo61W0f",
                            "public_id": "project_images/dNhIE21WW8XRtnIo61W0f"
                        }
                    ],
                    "video": "",
                    "materials_used": "Glue",
                    "tags": [
                        {
                            "name": "General"
                        }
                    ],
                    "category": [],
                    "likes": [],
                    "saved_by": [
                        "537c5432-daed-412a-8616-b140563ed8a7"
                    ],
                    "views_count": 2,
                    "comments": [
                        {
                            "id": 5,
                            "project": "9fac8df9-fe5c-46b0-ad50-d077e7f1f388",
                            "creator": {
                                "id": "537c5432-daed-412a-8616-b140563ed8a7",
                                "username": "dummy",
                                "avatar": "https://robohash.org/dummy"
                            },
                            "text": "hey",
                            "created_on": "2023-10-03T23:36:25.975529Z",
                            "replies": []
                        },
                        {
                            "id": 4,
                            "project": "9fac8df9-fe5c-46b0-ad50-d077e7f1f388",
                            "creator": {
                                "id": "537c5432-daed-412a-8616-b140563ed8a7",
                                "username": "dummy",
                                "avatar": "https://robohash.org/dummy"
                            },
                            "text": "hello again",
                            "created_on": "2023-10-03T23:33:50.130544Z",
                            "replies": []
                        },
                        {
                            "id": 3,
                            "project": "9fac8df9-fe5c-46b0-ad50-d077e7f1f388",
                            "creator": {
                                "id": "537c5432-daed-412a-8616-b140563ed8a7",
                                "username": "dummy",
                                "avatar": "https://robohash.org/dummy"
                            },
                            "text": "hello",
                            "created_on": "2023-10-03T23:32:44.291663Z",
                            "replies": []
                        },
                        {
                            "id": 1,
                            "project": "9fac8df9-fe5c-46b0-ad50-d077e7f1f388",
                            "creator": {
                                "id": "537c5432-daed-412a-8616-b140563ed8a7",
                                "username": "dummy",
                                "avatar": "https://robohash.org/dummy"
                            },
                            "text": "hello  world",
                            "created_on": "2023-10-03T23:26:15.827164Z",
                            "replies": []
                        }
                    ],
                    "created_on": "2023-09-30T16:18:57.224607Z",
                    "publish": {
                        "type": 4,
                        "visible_to": []
                    },
                    "comments_count": 3
                }
            ],
            "prev": null,
            "next": null,
            "count": 2
        },
        "created_on": "2023-09-30T16:24:14.918966Z"
    }
]
```

### CODE REVIEW

**Review by tuxology — APPROVED** [review]
Thanks 👍 LGTM 🌈

**Comment by tuxology** [comment]
@aqsaaqeel Can you rebase this to current master branch?

**Comment by aqsaaqeel** [comment]
> @aqsaaqeel Can you rebase this to current master branch?

I have rebased
Screenshot from 2023-10-05 02-17-03

**Comment by tuxology** [comment]
@aqsaaqeel Can you pull the latest master branch and then rebase? I see conflicts in `zubhub_backend/zubhub/projects/serializers.py`

**Comment by benndip** [comment]
Hello @aqsaaqeel nice work, but I really don't think the backend was missing a `comment_count` field because you see that your `comments_count` result and your `comments` are different. Above you have a comment_count of 3, but there are 4 comments. Same with the one above. And in your image.

Now if we go to the backend code of `models.py`, you will see that,  `StaffPick` is related to `Project` and `Project` is related to `Comment` with a related name of `comments`. So that is the count already. So this issue is to be solved from the frontend as it's just one line of code to adjust.

@tuxology @srish  I will release a PR that reloves this from the front end as it was just a missing key somewhere.

**Comment by benndip** [comment]
Please this is what I mean @aqsaaqeel  and @tuxology . `Projects` and `Staff Picked Projects` have different response structures. as seen below these screenshots

- Staff-Picked has the `comments` field on that particular project
Staff Picked

so we can pick the length of comments from there

- Projects have a `comments_count` field for the number of comments for that project
 
Projects

Hence the backend had no issue. It was just for the front end to reference both differently according to the fields from the backend, and the issue will be resolved.

**Comment by benndip** [comment]
PR here:
[https://github.com/unstructuredstudio/zubhub/pull/799](url)

**Comment by tuxology** [comment]
@benndip Ok, this is a good observation! I guess I was too quick in approving the PR 😅 @aqsaaqeel Sorry, we will close this since this will be resolved via #799 Thanks for your efforts!

**Comment by rak16** [comment]
@benndip If `comments_count` is not returning the correct value then isn't that something we should look into and resolve? Fixing it on the frontend with a conditional is merely a bandage, and not a well-rounded solution. 

What do you think @tuxology ?

**Comment by benndip** [comment]
No it's not an issue. The backend has an architecture.... it's the way the
Frontend was designed by the Project component. The Project component us
being used for two different structures of data so that is why the issue
came up. If we two different components to handle the two different
structures of projects and staff-picked projects, it will be okay. But the
conditional statement still works fine as it shows a little of SOLID
PRINCIPLES in React.

**Comment by rak16** [comment]
I feel this is a consistency issue and we should fix it on the backend. Nevertheless, even if we are okay with this, why is `comments_count` not the correct value if `comments` array is showing the right set of comments. Something is definitely not right on the backed side and should be addressed.

**Comment by benndip** [comment]
Hello Ravish, I understand your concern,  but I'm also a backend developer,
and I have tested well that there's no inconsistency with it. It's just a
code misunderstanding :). We could connect better and I'll show you what I
mean.

**Comment by rak16** [comment]
Sure, let's connect.

**Comment by benndip** [comment]
Are you available now @rak16 you can join here https://meet.google.com/uvn-dybq-gwp

**Pull request closed without merging**
