### PR TITLE
Add tests for activitylog backend

### LINKED ISSUE #668: Add Model and Views tests for "activitylog" backend Django app
Tests to the activitylog app in the django backend will help in knowing when there are breaking changes, hence improved user experience.
Screenshot_20230314-193758

### PR DESCRIPTION
**Pull request by Collins-Omariba**
## Summary

Addition of model and views tests for the activitylog django backend app.
Closes #668 

## Changes

- Add tests folder to activity log
- Add test_models, test_views & __init__.py file insde the tests folder.

## Screenshots
All tests passed.
The failed test is in another app , hence I decided not to change anything there(I will open an issue on it immediately after this review)

Screenshot (91)

### CODE REVIEW

**Comment by tuxology** [comment]
Wohoo! This is awesome 🎉 First tests. Thanks @Collins-Omariba I'll review this soon!

**Comment by Collins-Omariba** [comment]
Great. Am planning on adding tests for all the backed apps with none.

**Comment by tuxology** [comment]
@Collins-Omariba Just FYI, continue on this. This is important work, but we will take a bit of time to merge this since its not critical at the moment, I will circle back in a while to merge this!

**Comment by Collins-Omariba** [comment]
I think the other test in the creators app that was failing has been fixed by #701

**Review by tuxology — APPROVED** [review]
LGTM 🌈

**Pull request merged**
