### PR TITLE
Private mode

### PR DESCRIPTION
**Pull request by NdibeRaymond**
* Added Private mode
* Overhauled creator tags
* Added migrated from boolean published to a more robust
  publishing rules (Draft, Preview, Authenticated users, Public)
* Wrote Data migrations
* Made improvements to the codebase
* Added rich-text support to project description
* Refactored Project Creation
* Removed unnecessary models and fields from the admin site
* Improved the project card

### CODE REVIEW

**Comment by NdibeRaymond** [comment]
Merge conflicts are yet to be fixed. DO NOT MERGE. This is for review only @tuxology

**Comment by NdibeRaymond** [comment]
waiting for @tuxology final thumbs up before merging this

**Comment by tuxology** [comment]
OK @NdibeRaymond  lets go! Lets merge this one and the we will create separate issues to improve upon this.

**Review by tuxology — APPROVED** [review]
Lets merge this. I've tested this twice till now and the tasks we needed in private mode work. We will only know its full impact when we merge in main Zubhub.

**Pull request merged**
